// Package dnsredirect points the router's dnsmasq at the sing-box DNS inbound
// so FakeIP works for LAN clients (OpenWrt). On other platforms the user has
// to point clients or the DNS proxy at the DNS listen address manually.
package dnsredirect

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/Chistovik92/hydravpn-router/internal/config"
)

// Redirect manages a dnsmasq drop-in file.
type Redirect struct {
	ConfDir string // dnsmasq conf-dir, default /tmp/dnsmasq.d
	Restart func() error
	OnLog   func(level, message string)
}

// New returns a Redirect for OpenWrt paths.
func New(onLog func(level, message string)) *Redirect {
	return &Redirect{
		ConfDir: "/tmp/dnsmasq.d",
		OnLog:   onLog,
		Restart: func() error { return exec.Command("/etc/init.d/dnsmasq", "restart").Run() },
	}
}

// Supported reports whether dnsmasq can be reconfigured on this system.
func (r *Redirect) Supported() bool {
	st, err := os.Stat(r.ConfDir)
	return err == nil && st.IsDir()
}

func (r *Redirect) file() string { return filepath.Join(r.ConfDir, "hydravpn-router.conf") }

// Content is the dnsmasq drop-in: every upstream query goes to sing-box.
func Content() string {
	return fmt.Sprintf("# generated by hydravpn-router, removed on stop\nno-resolv\nserver=%s\n", config.DNSListenAddress)
}

// Apply installs the drop-in and restarts dnsmasq if it changed.
func (r *Redirect) Apply() error {
	if !r.Supported() {
		r.log("warn", "dnsmasq conf-dir %s not found: point clients or your DNS proxy at %s for FakeIP", r.ConfDir, config.DNSListenAddress)
		return nil
	}
	want := []byte(Content())
	if cur, err := os.ReadFile(r.file()); err == nil && string(cur) == string(want) {
		return nil
	}
	if err := os.WriteFile(r.file(), want, 0644); err != nil {
		return err
	}
	r.log("info", "dnsmasq now forwards DNS to %s", config.DNSListenAddress)
	return r.restart()
}

// Remove deletes the drop-in and restarts dnsmasq if it was installed.
func (r *Redirect) Remove() error {
	if err := os.Remove(r.file()); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	r.log("info", "dnsmasq forwarding removed")
	return r.restart()
}

func (r *Redirect) restart() error {
	if r.Restart == nil {
		return nil
	}
	if err := r.Restart(); err != nil {
		return fmt.Errorf("restart dnsmasq: %w", err)
	}
	return nil
}

// Wanted reports whether the configuration asks for the redirect.
func Wanted(cfg *config.Config) bool {
	return cfg.Settings.FakeIPEnabled && !cfg.Settings.DontTouchDHCP
}

func (r *Redirect) log(level, format string, args ...interface{}) {
	if r.OnLog != nil {
		r.OnLog(level, "[dnsredirect] "+strings.TrimSpace(fmt.Sprintf(format, args...)))
	}
}
